server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 0.5

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable auto-discovery of routes
          lower-case-service-id: true  # Use lower case service IDs for routes
      route:
        - id: keycloak-admin-client
          uri: lb://keycloak-admin-client
          predicates:
            - Path=/**

        - id: keycloak-admin-client-docs
          uri: lb://keycloak-admin-client
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/**,/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true