spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/project
          jwk-set-uri: http://localhost:8080/realms/project/protocol/openid-connect/certs
  application:
    name: keycloak-admin-client

server:
  port: 8082

keycloak:
  realm: project
  resource: keycloak
  auth-server-url: http://localhost:8080/
  credentials:
    username: admin
    password: 123
    client-id: keycloak
    secret: 9zDTopbhwUBDVK8jXhENjSiZC0ptOZUS
    provider: secret

springdoc:
  swagger-ui:
    oauth:
      client-id: keycloak
      client-secret: 9zDTopbhwUBDVK8jXhENjSiZC0ptOZUS
      realm: project
    tags-sorter: alpha

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web: debug